### ISSUE TITLE
Problem reading using an ESP32Thing

### ISSUE THREAD

**Issue by f34rdotcom** [sparkfunX/QWIIC_RFID_ID-XXLA#1]
I have been unable to read back from the device. I have multiple devices on an i2c bus and other devices do read so I am leaning towards an issue in this firmware not being compatible with esp-idf i2c driver.

When I write to its address 0x7d it does report an ACK that and so my i2c scanner does detect the device successfully. If however I try and read by 10 bytes from the device it end up with a timeout from the i2c driver on the esp32. It also seems to take a long time for the ATINY to ACK the address byte when reading. If I write to the address the ATINY does not delay the ACK.

I have disabled PULL UP's on all the devices on my i2c bus and turn on pullup on the GPIO pins on the ESP32

It is not clear what firmware is on the QWIIC_RFID_ID but it was within the past few weeks purchased from sparkfun.

Any help/suggestions appreciated.

```
i2c_config_t conf;
conf.mode = I2C_MODE_MASTER;
conf.sda_io_num = GPIO_NUM_4;
conf.scl_io_num = GPIO_NUM_2;
conf.sda_pullup_en = GPIO_PULLUP_ENABLE;
conf.scl_pullup_en = GPIO_PULLUP_ENABLE;
conf.master.clk_speed = speed; 
ESP_ERROR_CHECK(i2c_param_config(I2C_NUM_0, &conf));
ESP_ERROR_CHECK(i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0));

uint8_t temp[32];
i2c_cmd_handle_t cmd = i2c_cmd_link_create();
i2c_master_start(cmd);
i2c_master_write_byte(cmd, (0x7d << 1) | I2C_MASTER_READ, true);
ESP_ERROR_CHECK(i2c_master_read(cmd, temp, 9, ACK_VAL));
ESP_ERROR_CHECK(i2c_master_read_byte(cmd, temp+9, NACK_VAL));
i2c_master_stop(cmd);
espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 100/portTICK_PERIOD_MS);
if (espRc == ESP_OK) {
  printf("OK);
} else {
  printf("FAIL");      
}
i2c_cmd_link_delete(cmd);

```
The resulting capture.
![screenshot](https://user-images.githubusercontent.com/2042644/47389532-e0051480-d6c9-11e8-811d-b411b42f5362.png)

**Comment by edspark** [comment]
Hmmm...nothing comes to mind off the top of my head. I'll take a gander at this today and hopefully find an answer for you.

**Comment by edspark** [comment]
I hooked up my a Sparkfun ESP32 Thing to my Qwiic RFID and was able to read back from two separate tags using pins 21/22 as SDA/SCL respectively with no other devices attached:
![image](https://user-images.githubusercontent.com/18684691/47452957-b65ef280-d788-11e8-9ba8-443ea3dfdac1.png)

My first thought is that there's some sort of cold joint on the UART pin from the RFID reader to the product. I did however test each one of the boards personally, but it is possible that something got bumped in transit or through use.  Below is an image of the header for the RFID module with the pad for the UART pin circled in blue(pin 9): 
![image](https://user-images.githubusercontent.com/18684691/47453548-3e91c780-d78a-11e8-89fb-c8445021261f.png)

Let me know if there's anything else I can help with.

**Comment by f34rdotcom** [comment]
The problem I am seeing is on the i2c bus portion from the ATTINY85 chip not the UART pins. As best I can describe the ATTINY85 is not pulling down the SDA line after the 8th bit to indicate it received the READ command with address.

**Comment by f34rdotcom** [comment]
Just an update.

I am able to read the bytes using an ESP32Thing provided I set the i2c timeout after installing the i2c driver. The default value is 6400.
  `i2c_set_timeout(I2C_NUM_0, 32000);`

This fixes the "clock stretching" that is happening from the ATTINY85 board. I am however still see many random bad responses with NAK errors and AFAIK I have no way of detecting if a message had NAK errors. I end up with a successful read but the data is full of 0xff bytes. These issues seem very specific to esp-idf so I am going to close this. If you have some ability to help me confirm and help determine how to fix this any help would be appreciated.

![image](https://user-images.githubusercontent.com/2042644/47829039-c192bf00-dd42-11e8-9e47-b1399a61b875.png)

RFID:80ffffffffffffffffff
I (5539912) MYI2CSENS: myi2c-rfid 4294967295,42949672
RFID:000000000000000001c1
I (5540412) MYI2CSENS: myi2c-rfid 449,0
RFID:000000000000000001c1
I (5540912) MYI2CSENS: myi2c-rfid 449,0
RFID:000000000000000001c1
I (5541412) MYI2CSENS: myi2c-rfid 449,0
RFID:000000000000000001c1
I (5541912) MYI2CSENS: myi2c-rfid 449,0
RFID:0000000000007fffffff
I (5542412) MYI2CSENS: myi2c-rfid 2147483647,0

**Comment by edspark** [comment]
I'm going to close this for now @f34rdotcom. If you discover something please feel free to open it back up.
